# Generated by Django 3.1.2 on 2020-10-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201011_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
