# Generated by Django 3.1.2 on 2020-10-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201011_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
