# Generated by Django 3.1.2 on 2020-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201012_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task_time',
            field=models.IntegerField(null=True),
        ),
    ]
